### ISSUE TITLE
how to solve "cannot install react-native-responsive-screen"

### ISSUE THREAD

**Issue by luthfidc03** [marudy/react-native-responsive-screen#10]
@marudy . sir,  I have issue when install this package.  how to solve this issue?
![1](https://user-images.githubusercontent.com/18740863/44415085-b92b4480-a599-11e8-8630-1ace134b4bb0.png)

**Comment by marudy** [comment]
Hi there,

I replied to your email as well but I received a bouncer that the email address does not exist.

From what I see the package is installed OK without a problem but it searches for React Native 0.47. This should not happen, because the package works for previous RN versions as well.

I'm fixing it now and issuing a new release soon.

**Comment by marudy** [comment]
It should be fixed now, please have a look.

**Comment by marudy** [comment]
Hey @luthfidc03, did you try out the new version?
