### ISSUE TITLE
Unable to adapt for Android device

### ISSUE THREAD

**Issue by songxiaoliang** [marudy/react-native-responsive-screen#14]
Hi, I am very happy to use your library. When I first saw the article, I was so excited. So I can't wait to try it out in the project, but after using it, I found that I didn't get the result.The following is the code, and the sample diagram：
      <Container
        height={ heightPercentageToDP('81.16%') }
        style={style}>
       <Image source={....}  />
       ......
       </Container>

<img width="484" alt="bdcc7190-7210-4dd3-8335-59e39ba5393d" src="https://user-images.githubusercontent.com/6975588/44841531-1dbf6100-ac76-11e8-8a5c-f59297814beb.png">
<img width="484" alt="f45c60dd-2be6-412a-a8c1-d6f3411a34ae" src="https://user-images.githubusercontent.com/6975588/44841742-a938f200-ac76-11e8-839a-8bc293e7c188.png">

The same setting results in a blank gap at the bottom. So how to solve it and adapt it? I am a Chinese developer, my English is not perfect, I hope to understand, I look forward to your reply.
thanks.

**Comment by marudy** [comment]
Hi there,

I got your problem yes. As I said, it's not an issue with the library. The library adapts the area you want properly. The fact that it doesn't match to another device it's because of the library, but because the other elements in your view. There are 2 ways to go about it overall:

1. Try to pass specific height as well to all other view element's with the use of this library as proposed previously
2. If you can't do 1. then probably it makes no sense to use the library for this screen or for all screens that have elements where their height is not controlled by you. In this case it would be better to go with flex or even "normal" percentages relative to their parent elements.

**Comment by marudy** [comment]
Hi there,

did you find a way to achieve the result you wanted? I could also help if you are willing to share some code :)

Cheers,
Tasos

**Comment by songxiaoliang** [comment]
@marudy Hi there,

It doesn't matter with the bottom navigator, because the bottom navigator is absolutely positioned at the bottom, not at the same level as the above layout. The problem now is to set the height of the active module, but the height displayed on different devices is different. This blank gap will appear. The effect I want is that on any device, as with the first display, the part of the active module above is guaranteed to be outside the navigator, and I look forward to your reply.

**Comment by marudy** [comment]
Hi.

From what I see it's not a problem with library but instead how your CSS is structured overall. If you give me access to your code or paste a part it somewhere online (i.e. in expo snack) I will be able to help you out :-)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by marudy** [comment]
@songxiaoliang,

Any update on this one? Wanna share some code with me?
