### ISSUE TITLE
Flow type support?

### ISSUE THREAD

**Issue by sanjaypojo** [marudy/react-native-responsive-screen#32]
We actively use the library and really like it 👍 We've been trying to improve our flow coverage and were wondering if you could add flow types to the library?

Thanks!

**Comment by marudy** [comment]
Hey @sanjaypojo and sorry for the late response. Happy new year!

Yeah so flow support would be great indeed but I don't think I would be able to get the time to work on it soon. I would welcome a PR though if you are up for it! If you have a look at the package it's really small; so it won't be difficult to do it yourself. If you do open a PR please ping me explicitly in order to review and release it.

Thanks

**Comment by sanjaypojo** [comment]
Hey @marudy finally had a minute so I submitted a PR. Do take a look and let me know if you need any changes :)
