### ISSUE TITLE
When would you use normal styling?

### ISSUE THREAD

**Issue by bkkwok** [marudy/react-native-responsive-screen#7]
First off, thank you for creating this lovely package for the community.  It is so simple to use and very effective for achieving responsiveness.  This isn't an issue, as it is a question.  

Are there any instances where you would use normal styling over heightToPercentageDP or widthToPercentageDP when trying to achieve full responsiveness?

I've been using this package for almost every attribute in react-native (fontSize, margin, padding, width , height).

**Comment by marudy** [comment]
Hi @bkkwok,

thanks so much for your kind words :-) I am really very glad that you have found this package useful!

Now, about the package methods, I use them myself for almost every attribute in react-native development. There are a couple of cases that you might not need them:
* When your position style property (bottom, right etc) has a value of 0
* With property `border-radius` when I need a big value. I have noticed that if you have `border-radius: 250` or `border-radius: 25000000000` the visual outcome is the same. But if I need a small value, then I use the package methods.

Now and a bit off topic from your original question I would like to share how I personally use the package methods in some ways that might not be obvious!
* I always configure my container View component to `flex: 1`
* I try to use flex whenever I can
* I always use `widthPercentageToDP` and `heightPercentageToDP` instead of "normal" percentage values, even for 100%. I have noticed that there is a difference which is visible by eye. I haven't searched how RN percentage gets calculated and rendered but it's not 100% accurate in my experience (at least in Android).
* I have found out that the value 10DP is equivalent with `heightPercentageToDP('1.6%')` in an average mobile phone. So if you have a project with DP and want to change it to responsive, you can use this analogy as a guide :-)
